config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "home#index"
  resources :menus
  resources :users
  resources :order_foods
  resources :orders
  get "/clerks_detail" => "users#show", as: :clerk
  delete "/clerks_detail/:id" => "users#destroy", as: :destroy_clerk
  get "/allorders" => "orders#show", as: :new_allorder
  get "/cards" => "order_foods#show", as: :new_card
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :order_foods
  belongs_to :user

  validates :name, presence: true
  validates :price, presence: true
  validates :menu_category, presence: true

  def self.breakfast
    all.where(:menu_category => "Breakfast")
  end

  def self.lunch
    all.where(:menu_category => "Lunch")
  end

  def self.dinner
    all.where(:menu_category => "Dinner")
  end

  def self.beverages
    all.where(:menu_category => "Beverages")
  end

  def self.snacks
    all.where(:menu_category => "Snacks")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_foods

  before_save :set_total
  before_save :set_total_order

  def total
    order_foods.collect { |order_food| order_food.valid? ? order_food.unit_price * order_food.quantity : 0 }.sum
  end

  def total_order
    order_foods.collect { |order_food| order_food.id }.count
  end

  private

  def set_total
    self[:total] = total
  end

  private

  def set_total_order
    self[:total_order] = total_order
  end
end

app/models/order_food.rb
class OrderFood < ApplicationRecord
  belongs_to :menu
  belongs_to :order

  before_save :set_unit_price
  before_save :set_subtotal

  def unit_price
    menu.price
  end

  def subtotal
    unit_price * quantity
  end

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/orderfood.rb
class Orderfood < ApplicationRecord
  belongs_to :menu
  belongs_to :order

  before_save :set_subtotal
  before_save :set_unit_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      menu.price
    end
  end

  def subtotal
    unit_price * quantity
  end

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :menus

  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  def is_clerk?
    role == "Clerk" ? true : false
  end

  def is_owner?
    role == "Owner" ? true : false
  end

  def is_customer?
    role == "Customer" ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in
  include ApplicationHelper

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to menus_path
    else
      render "index"
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    @menus = Menu.all
    @order_food = current_order.order_foods.new
    #render plain: Menu.all.map { |menu| menu.to_pleasent_string }.join("\n")
    render "index"
  end

  def new
    render "menus/new"
  end

  def show
    @menus = Menu.where(:id => Menu.find(params[:id]))
  end

  def create
    new_menu = Menu.new(menu_params)
    check_save_condition(new_menu)
  end

  def update
    up_menu = Menu.find(params[:id])
    up_menu.update(menu_params)
    check_save_condition(up_menu)
  end

  def destroy
    Menu.find(params[:id]).destroy
    redirect_to menus_path
  end

  private

  def menu_params
    params.permit(:name, :description, :menu_category, :price, :availability_status).tap do |menu|
      menu[:user_id] = current_user.id
    end
  end

  private

  def check_save_condition(menu)
    if menu.save
      redirect_to menus_path
    else
      flash[:error] = menu.errors.full_messages.join(", ")
      redirect_to menus_path
    end
  end
end

app/controllers/order_foods_controller.rb
class OrderFoodsController < ApplicationController
  def create
    order = current_order
    @order_food = order.order_foods.new(order_params)
    order.save
    session[:order_id] = order.id
    check_create_condition(order)
  end

  def show
    @order_foods = OrderFood.where(:order_id => current_order.id)
    @orders = current_user.orders
  end

  def update
    up_order = OrderFood.find(params[:id])
    up_order.update(update_params)
    check_save_condition(up_order)
  end

  def destroy
    order_food = current_order.order_foods.find(params[:id])
    order_food.destroy
    redirect_to new_card_path
  end

  private

  def update_params
    params.permit(:quantity)
  end

  private

  def order_params
    params.require(:order_food).permit(:menu_id, :quantity)
  end

  private

  def check_save_condition(up_order)
    if up_order.save
      redirect_to new_card_path
    else
      flash[:error] = menu.errors.full_messages.join(", ")
      redirect_to new_card_path
    end
  end

  def check_create_condition(order)
    if order.save
      flash[:notice] = "menu added to cart successfully"
      redirect_to menus_path
    else
      flash[:error] = order.errors.full_messages.join(", ")
      redirect_to menus_path
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    Order.new(user_id: current_user.id, status: 0)
  end

  def show
    @order = Order.all
  end

  def update
    uporder = Order.find(params[:id])
    if uporder.status == 0
      order_placed(uporder)
    elsif uporder.status == 1
      order_delivered(uporder)
    end
  end

  def destroy
    Order.find(params[:id]).destroy
    redirect_to new_allorder_path
  end

  private

  def order_placed(uporder)
    uporder.status = 1
    if uporder.save
      redirect_to new_card_path
    else
      flash[:error] = Order.errors.full_messages.join(", ")
      redirect_to new_card_path
    end
  end

  private

  def order_delivered(uporder)
    uporder.status = 2
    if uporder.save
      redirect_to new_allorder_path
    else
      flash[:error] = Order.errors.full_messages.join(", ")
      redirect_to new_allorder_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    session_error(user)
  end

  def destroy
    session[:current_user_id] = nil
    session[:order_id] = nil
    redirect_to "/"
  end

  private

  def session_error(user)
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Your login attempt is invalid. Try again"
      redirect_to new_sessions_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "users/new"
  end

  def show
    @user = User.where(:role => "Clerk")
  end

  def create
    user = User.new(create_user)
    create_error(user)
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to clerk_path
  end

  private

  def create_user
    params.permit(:name, :role, :email, :password)
  end

  private

  def create_error(user)
    if user.save
      redirect_to "/"
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    if Order.where(:user_id => current_user.id).exists? && !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new(user_id: current_user.id, status: 0)
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    current_user_id ? @current_user = User.find(current_user_id) : nil
  end
end

app/views/allorders/show.html.erb
<h4>hello</h4>

<% @order.each do |item| %>
  <tr>
      <td>Order id :<%= item.id %>, </td>
      <td>User id : <%= item.user_id %>, </td>
      <td>Total : <%= item.total %>, </td>
    <% if item.status == "Placed" %>
      <td>Status : <%= item.status %> </td>
      <%= link_to '<button class="Menu-button" type="button">Delivered</button>'.html_safe, update_allorder_path(item.id), method: :put,:onclick => "alert('Are U sure')" %>
    <% else %>
      <td>Status : <%= item.status %> </td>
    <% end %>
  </tr>
  <br/>
<% end %>

app/views/cards/show.html.erb
<% @orderfoods.each do |item| %>

    <ul>
        <li>Name : <%= item.menu.name %></li>
    </ul>
    <h3>Price : <%= item.menu.price %></h3>
    <h3>Quantity : <%= item.quantity %></h3>
    <h5>Subtotal : <%= item.subtotal %></h5>

    <%= link_to '<button class="Menu-button" type="button">Remove</button>'.html_safe, orderfood_path(item), method: :delete %>
    <br>

<% end %>

<h3>Your current card value has a total of: <%= current_order.total %></h3>
<% if Order.where(:user_id => current_user.id).exists? %>
    <%= link_to '<button class="Menu-button" type="button">Place Order</button>'.html_safe, order_path(current_order.id), method: :put,:onclick => "alert('Order Placed, will be delivered shortly')" %>
<% else %>
    <h1>please add values to card</h1>
<% end %>

app/views/home/index.html.erb
<h1 class="HomePage-title">Welcome to Cafeteria Manager</h1>

<h3 class="Home-authenticate">If you are a new user,</h3>

<h3 class="Home-authenticate"><%= link_to "sign up here", new_user_path %></h3>

<h3 class="Home-authenticate">If you are a existing user,</h3>

<h3 class="Home-authenticate"><%= link_to "sign in here", new_sessions_path %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
      Welcome <%= @current_user.name %>!
      <%= link_to "Back to menu", menus_path%>
      <%= link_to "Sign-out", destroy_session_path, method: "delete"%>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end%>

    <% if flash[:notice] %>
      <p class="Flash-error">
        <%= current_order.total_order%>
        <%= flash[:notice] %>
      </p>
    <% end%>

    <%= yield %>
  </body>
</html>

app/views/menus/_add-menu-section.html.erb
<section class="MenuSection">
  <div>
    <p class="MenuSectionTitle-text"><%= section_title%></p>
  </div>

  <section class="UsersOwner">
    <%= form_with url: "/menus",method: "post" do |form| %>

      <div class="AddMenu-section">
        <p class="AddMenu-label">Menu Category </p>
        <%= form.select :menu_category,options_for_select([["Select One",""],"Breakfast","Lunch","Dinner","Beverages","Snacks"]) ,{},{:class => "AddMenu-text"}%>
      </div>

      <div class="AddMenu-section">
        <p class="AddMenu-label">Availability Status </p>
        <%= form.select :availability_status, options_for_select([["Select One",""],"Available","Unavailable"]) ,{},{:class => "AddMenu-text"}%>
      </div>

      <div class="AddMenu-section">
        <p class="AddMenu-label">Menu Name </p>
        <%= form.text_field :name, class: "AddMenu-text" %>
      </div>

      <div class="AddMenu-section">
        <p class="AddMenu-label">Description </p>
        <%= form.text_field :description, class: "AddMenu-text" %>
      </div>

      <div class="AddMenu-section">
        <p class="AddMenu-label">Price </p>
        <%= form.text_field :price, class: "AddMenu-text", step: "any" %>
      </div>

      <div class="AddMenu-section">
        <%= form.submit "Add",class: "AddMenu-button" %>
      </div>
    <% end %>
  </section>
</section>

app/views/menus/_menus-section.html.erb
<section class="MenuSection">
  <div class="MenuSectionTitle">
    <p class="MenuSectionTitle-text"><%= section_title%></p>
  </div>

  <ul>
    <% if menus.empty? %>
      <p class="MenuItem MenuItem-NotAvilable">Not Available</p>
    <% else %>
      <% menus.each do |menu|%>
        <li class="MenuItem">
          <div class="MenuItem-container">
            <label>

              <p class="MenuItem-text">
                <% if @current_user.is_clerk? || @current_user.is_owner? %>
                  <%= link_to menu.name, menu_path(menu.id) %>
                <% else %>
                  <span class="AlignLeft"> <%= menu.name %> </span>
                <% end %>
                <span class="AlignRight"> Rs <%= menu.price %> </span>
              </p>

              <p class="MenuItemDescription-text">
                <%= menu.description%>
                <p class="MenuButtom-owner">
                  <% if @current_user.is_clerk? || @current_user.is_owner? %>
                    <%= link_to '<img src="trash.svg" class=AlignRight">'.html_safe, menu_path(menu.id), method: :delete,:onclick => "alert('Are you sure')" %>
                  <% end %>
                </p>
              </p>

              <p class="MenuAddToCard">
                <% if @current_user.is_customer? %>
                  <% if menu.availability_status == "Available"%>
                    <%= form_for @order_food do |form| %>
                      <%= form.hidden_field :menu_id, :value => menu.id %>
                      <%= form.number_field :quantity,class: "AddMenu-text",placeholder: "Add quantity", :min => 1 %>
                      <%= form.submit "Add to Cart", :class => "Menu-button" %>
                    <% end %>
                  <% else %>
                    <p>Unavailable</p>
                  <% end %>
                <% end %>
              </p>

            </label>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>

</section>

app/views/menus/index.html.erb
<main>
  <article>
    <section class="MenuPage-title">
      <% if @current_user.is_clerk? || @current_user.is_owner? %>
        <%= link_to '<button class="AddMenu-button AlignRight" type="button">Add Menu</button>'.html_safe, new_menu_path %>
      <% end %>
      <% if @current_user.is_owner? %>
        <%= link_to '<button class="AddMenu-button AlignLeft" type="button">Clerks Detail</button>'.html_safe, clerk_path %>
      <% end %>
      <% if @current_user.is_customer? %>
        <p class="AlignRight"><%= current_order.total_order %></p>
        <%= link_to '<img src="carts.svg" class="AlignRight">'.html_safe, new_card_path%>
      <% end%>
      <h1>Cafeteria Management</h1>
    </section>

    <%= render partial: "menus-section", locals: {
      section_title: "Breakfast",
      menus: Menu.breakfast
    } %>

    <%= render partial: "menus-section", locals: {
      section_title: "Lunch",
      menus: Menu.lunch
    } %>

    <%= render partial: "menus-section", locals: {
      section_title: "Dinner",
      menus: Menu.dinner
    } %>

    <%= render partial: "menus-section", locals: {
      section_title: "Beverages",
      menus: Menu.beverages
    } %>

    <%= render partial: "menus-section", locals: {
      section_title: "Snacks",
      menus: Menu.snacks
    } %>

    <% if @current_user.is_clerk? || @current_user.is_owner? %>
       <%= link_to '<button class="AddMenu-button AlignRight" type="button">All Orders</button>'.html_safe, new_allorder_path%>
    <% end%>

  </article>
</main>

app/views/menus/new.html.erb
<%= render partial: "add-menu-section", locals: {
    section_title: "Add Menu Here"
} %>

app/views/menus/show.html.erb
<section>
  <% if @current_user.is_clerk? || @current_user.is_owner? %>
    <% @menus.each do |item|%>
      <p class="MenuLabel">Name : <%= item.name %></p>
      <p class="MenuLabel">Price : <%= item.price%></p>
      <p class="MenuLabel">Description : <%= item.description%></p>
      <%= form_with url: "/menus/#{item.id}", method: "put",class: "MenuUpdate" do |form| %>
        <%= form.text_field :price, placeholder: "Price", class: "AddMenu-text", step: "any" %>
        <%= form.text_field :description, placeholder: "Description", value: item.description, class: "AddMenu-text"%>
        <%= form.select :availability_status, options_for_select([["Select One",""],"Available","Unavailable"]) ,{},{:class => "AddMenu-text"}%>
        <%= form.submit "Update", :class => "Menu-button" %>
      <% end %>
    <% end %>
  <% else %>
    <% @menus.each do |item|%>
      <p class="MenuLabel">Name : <%= item.name %></p>
      <p class="MenuLabel">Price : <%= item.price%></p>
      <p class="MenuLabel">Description : <%= item.description%></p>
    <% end %>
  <% end %>
</section>

app/views/order_foods/_display-order-items-section.html.erb
<section class="OrderFood-main">
  <div class="MenuSectionTitle">
    <p class="MenuSectionTitle-text"><%= section_title%></p>
  </div>

  <table class="OrderFood-table">
    <tr class="OrderFood-tableHeader">
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Subtotal</th>
      <th>Update items</th>
      <th>Remove items</th>
    </tr>
    <tr>
      <% @order_foods.each do |item| %>
        <tr class="OrderFood-tablecontent">
          <td><%= item.menu.name %></td>
          <td><%= item.menu.price %></td>
          <td><%= item.quantity %></td>
          <td><%= item.subtotal %></td>
          <td>
            <%= form_with url: "/order_foods/#{item.id}", method: "put",class: "MenuUpdate" do |form| %>
              <%= form.number_field :quantity,class: "AddMenu-text", :value => item.quantity, :min => 1 %>
              <%= form.submit "Update", :class => "Menu-button" %>
            <% end %>
          </td>
          <td><%= link_to '<button class="Menu-button" type="button">Remove</button>'.html_safe, order_food_path(item), method: :delete %></td>
        </tr>
      <% end %>
    </tr>
  </table>

  <p class="OrderFood-result">Your current card value has a total of: <%= current_order.total %></p>
  <p>
    <% if Order.where(:id => current_order.id).exists? %>
      <%= link_to '<button class="Add-button" type="button">Place Order</button>'.html_safe, order_path(current_order.id), method: :put,:onclick => "alert('Order Placed, will be delivered shortly')" %>
    <% else %>
      <tr class="OrderFood-result">please add values to card</tr>
    <% end %>
  </p>
</section>

app/views/order_foods/_order-history-section.html.erb
<section class = "Order-history">
  <div class="MenuSectionTitle">
    <p class="MenuSectionTitle-text"><%= section_title%></p>
  </div>

  <table class = "OrderHistory-table">
    <tr class="OrderHistory-header">
      <th> Order id </th>
      <th> No. of items </th>
      <th> Total </th>
      <th> Orders items </th>
    </tr>
    <% @orders.each do |item|%>
      <% if item.status == 2 %>
        <tr class="OrderHistory-content">
          <td><%= item.id %></td>
          <td><%= item.total_order%></td>
          <td><%= item.total %></td>
          <td>
            <% item.order_foods.each do |food|%>
              <p><li><%= link_to 'check menu' , menu_path(food.menu_id) %></li></p>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</section>

app/views/order_foods/show.html.erb
<section>
    <%= render partial: "display-order-items-section", locals: {
        section_title: "Cart items"
    } %>

    <%= render partial: "order-history-section", locals: {
        section_title: "Past Order History"
    } %>
</section>

app/views/orderfoods/show.html.erb
<section class="OrderFood-main">
    <% @orderfoods.each do |item| %>

        <section class="OrderFood-list">
            <p>Name : <%= item.menu.name %></p>
            <p>Price : <%= item.menu.price %></p>
            <p>Quantity : <%= item.quantity %></p>
            <p>Subtotal : <%= item.subtotal %></p>
            <%= link_to '<button class="Add-button" type="button">Remove</button>'.html_safe, orderfood_path(item), method: :delete %>
        </section>
        <br>

    <% end %>

    <p class="OrderFood-result">Your current card value has a total of: <%= current_order.total %></p>
    <p>
        <% if Order.where(:id => current_order.id).exists? %>
            <%= link_to '<button class="Add-button" type="button">Place Order</button>'.html_safe, order_path(current_order.id), method: :put,:onclick => "alert('Order Placed, will be delivered shortly')" %>
        <% else %>
            <p class="OrderFood-result">please add values to card</p>
        <% end %>
    </p>

</section>

app/views/orders/show.html.erb
<section class="Order-table-main">
  <table class="Order-table">
    <tr class="Order-tableHeader">
      <th>Order id</th>
      <th>User id</th>
      <th>Total</th>
      <th>status</th>
    </tr>

    <% @order.each do |item| %>
      <tr class="Order-tablecontent">
        <td><%= item.id %> </td>
        <td><%= item.user_id %> </td>
        <td><%= item.total %></td>
        <% if item.status == 1 %>
          <td>
            Placed
            <%= link_to '<button class= "Deliver-button" type="button">Delivered</button>'.html_safe, order_path(item.id), method: :put,:onclick => "alert('Are U sure')" %>
          </td>
        <% elsif item.status == 2 %>
          <td>Delivered </td>
        <% else %>
          <% item.destroy %>
        <% end %>
      </tr>
    <% end %>
  </table>
</section>

app/views/users/new.html.erb
<p class="NewUsersTitle">SignUp!</p>

<section class="UsersNew">
  <%= form_with url: users_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label">Role: </p>
      <%= form.select :role,options_for_select([["Select One",""],"Customer","Owner","Clerk"]) ,{},{:class => "Form-input"}%>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">First name: </p>
      <%= form.text_field :name, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Email: </p>
      <%= form.email_field :email, class: "Form-input"%>
    </div>
    <div class="Form-section">
      <p class="FormInput-label">Password: </p>
      <%= form.password_field :password, class: "Form-input"%>
    </div>
    <div class="Form-section">
      <%= form.submit "Sign-up!",class: "Form-submit" %>
    </div>
  <% end %>
</section>

app/views/users/show.html.erb
<p class="UserHeader">
  <%= link_to "Back to menu", menus_path%>
  <%= link_to "Sign-out", destroy_session_path, method: "delete"%>
</p>
<section class="Order-table-main">
  <table class="Order-table">
    <tr class="Order-tableHeader">
      <th>User id</th>
      <th>Name</th>
      <th>Remove Clerk</th>
    </tr>

    <% @user.each do |user|%>
      <tr class="Order-tablecontent">
        <td><%= user.id %> </td>
        <td><%= user.name %> </td>
        <td><%= link_to '<button class= "Deliver-button" type="button">Remove</button>'.html_safe, destroy_clerk_path(user.id), method: :delete,:onclick => "alert('Are U sure')" %></td>
      </tr>
    <% end %>
  </table>
</section>